### ISSUE TITLE
English translation?

### ISSUE THREAD

**Issue by hvanmegen** [BergenSoft/smart-nodes#2]
While my German understanding is quite ok, I wonder if everyone's is.. is there a way to use translation strings in modules like there and if not, would you be willing to accept an English translated version?

**Comment by BergenSoft** [comment]
NodeRed is able to support multiple languages for the nodes and also the documentation. But as it wasn't my first priority to make it multi-language I hadn't taken the time to find out how to use this feature.
A plain english solution I won't accept as some people definitely will need the German translation.

But I would really appreciate and accept it if you would send an pull-request which is enabling the multi-language feature and translate it in english.

**Comment by alexsahka** [comment]
> NodeRed is able to support multiple languages for the nodes and also the documentation. But as it wasn't my first priority to make it multi-language I hadn't taken the time to find out how to use this feature. A plain english solution I won't accept as some people definitely will need the German translation.
> 
> But I would really appreciate and accept it if you would send an pull-request which is enabling the multi-language feature and translate it in english.


Question: Why is the description in English here? It seems illogical to me if the nodes are in German.
![image](https://github.com/BergenSoft/smart-nodes/assets/7469537/c74614fa-fa44-49e0-a2a9-675418990afa)

**Comment by BergenSoft** [comment]
This text isn’t needed by the German users I know. And as already said, multi-language would be great, of course. And then the English description would make more sense.

**Comment by BergenSoft** [comment]
I started to implement the multi language feature. It it not finished yet, but I had to push the code because of a problem with node-red v4. So you can already test if it works. For example take a look to the central/compare/counter controls.

It would be great if you would provide a feedback if it is working as expected.

**Comment by BergenSoft** [comment]
It was really a lot of work, but now all translations should be included. In addition, the code has been optimized in many places and brought into a uniform structure.

**Comment by hvanmegen** [comment]
very nice, Gute Arbeit and such!
