### ISSUE TITLE
Mistake in code

### ISSUE THREAD

**Issue by mkotusz** [BergenSoft/smart-nodes#4]
I have been wanting to use your smart_heating-curve node.
When I deploy I get the following error - "TypeError: node_settings.setpoint.toFixed is not a function"

**Comment by mkotusz** [comment]
Sorry. That error was "TypeError: node_settings.temperature_outside?.toFixed is not a function"

**Comment by BergenSoft** [comment]
Thank you, I see an error and will fix it later. In the meantime, try to send the outside temperature as float, not as a string or integer.

**Comment by BergenSoft** [comment]
I had some time now and fixed it. It will take some time, untile NodeRed will find the update.
Let me know if it is working for you.

**Comment by mkotusz** [comment]
It isn't working properly. I send you screenshots from RedNode addon.
![heating_curve flow and debug](https://github.com/user-attachments/assets/c381d67b-82ee-4130-9617-67a7796bb17d)
![Node heating curve configuration](https://github.com/user-attachments/assets/a64b2871-aded-4a73-827e-09f1c01a2365)
![Outside temperature configuration](https://github.com/user-attachments/assets/379d6716-7442-4802-a9cb-d007a838f746)
![Target temperature configuration](https://github.com/user-attachments/assets/9b6e1114-dbad-471a-ac1f-0dfc367e5176)

**Comment by mkotusz** [comment]
The version of Smart_Node is 0.4.8

**Comment by BergenSoft** [comment]
Send this instead:
`
{
    „topic“: „temperature_outside“,
    „payload“: 22.0
}
`

The topic number, the part after `#` is not used in this node.

**Comment by BergenSoft** [comment]
One more hint: the last values were stored in a file and reloaded after the next start, that mens an invalid value will be loaded even after a restart. So make sure to send a valid `payload`, so that the error will disappear.

**Comment by mkotusz** [comment]
The error is reported after deploy and not during node startup. After sending JSON the error is still there.

**Comment by mkotusz** [comment]
Can you recreate the flow for yourself and check it?

**Comment by mkotusz** [comment]
Are you sure that in the heating-curve.js file on line 149 there should be "?" characters in the function call?

**Comment by BergenSoft** [comment]
It is working.
Please try to load the example flow:
Flow: https://github.com/BergenSoft/smart-nodes/blob/main/examples/heating-curve.json
![Picture](https://raw.githubusercontent.com/BergenSoft/smart-nodes/refs/heads/main/examples/heating-curve.png)

I'm still thinking that you are **not** sending the correct message.
topic `temperature_outside#5.0` is a valid topic, but the `#5.0` will be ignored from this node.
Send the temperature in the `payload` property.

**Comment by mkotusz** [comment]
I have uninstalled "Smart Nodes" and instaled it. The error is gone. The node "heating curve" works properly but only if offset is equal zero. I offset is greater zero the output of node is constant and equal 70 even if offset return to zero. Then the node have to be deleted from the flow and putted again there. Could you check it?

**Comment by mkotusz** [comment]
Can I expect an answer?

**Comment by BergenSoft** [comment]
Sorry, forgot to answer. I‘ll check it later.

**Comment by BergenSoft** [comment]
I found the problem. The config values for offset and slope were read as strings. I guess with integer it should have worked, but I didn't test the old code as I found the problem.
The new version is pushed to the server and will be available soon.
